---
##
# pcd-systems/common prepare
#

# ensure root user's ssh key
- { include: "{{ pcd_task_adduser }}", task: {
      name: "root",
      group: "root", 
      home: "/root",
      key: "{{ ansible_ssh_private_key_file }}",
    }
  }
