---
##
# pcd-systems/common prepare
#

# ensure root user's ssh key
- { include: "{{ pcd_task_add_user }}", task: {
      name: "root",
      group: "root", 
      home: "/root",
      key: "{{ ansible_ssh_private_key_file }}",
    }
  }

# ensure "nogroup" exists as a system group
- name: add the group "nogroup"
  group: name=nogroup system=yes state=present