---
##
# pcd-systems/common prepare
#

# ensure root user's ssh key
- { include: "{{ pcd_task_add_user }}", task: {
      name: "root",
      group: "root", 
      home: "/root",
      key: "{{ ansible_ssh_private_key_file }}",
    }
  }
  
- name: allow ssh PubkeyAuthentication
  lineinfile: 
    dest={{ os_sshd_config_file }}
    regexp="^PubkeyAuthentication"
    line="PubkeyAuthentication yes"
    state=present
  notify: 
    - sshd restart

# ensure user common groups "nogroup" exists as a system group
- name: add common groups
  group: name={{ item }} system=yes state=present
  with_items:
    - nogroup
    - ansible
  
  
# Ensure /etc/ansible metadirs 
##############################

- name: ensure ansible-pcd metadirs
  file: 
    path={{ item }}
    state=directory
    owner=root
    group=ansible
    mode=0755
  with_items:
    - /etc/ansible
    - /etc/ansible/conf.d