
# common apache handlers

- name: apache restart
  service: name={{ }} state=restarted

- name: apache reload
  command: sudo /usr/sbin/apache2ctl -k graceful
  when: "ansible_os_family == 'RedHat'"
  
- name: apache reload
  action: command sudo /usr/sbin/apachectl -k graceful
  when: "ansible_os_family == 'RedHat'"
  