---
###
# development environment
#
# automates the provisioning of minimalistic production environment meant to 
# run in a local or lab VM. The development environment  is stripped of 
# unecessary components such as banckups and awstats statistics.
#
# Assumes 
#   * the PCDROOT/inventory/development.hosts is used
#   * a VM is running as "debian.dev" with a /shared directory pointing to your 
#     development folder.
#
# Visiting http://debian.dev/ will bring up a directory listing of the /shared folder 
#  + NOTE apache's autoindex module is enabled (via development.yml in group_vars)
#
###

# provision development system(s)
- { include: pcd_system.yml }


# configure development system(s) as a webserver
- name: "webserver configuration"
  hosts: webservers
  remote_user: root
  
  roles:
    - {role: pcd-common, tags: ['prepare','configure']}
    - pcd-services/mysql
    - pcd-services/apache
    
    
# deploy development website

- name: "deploy development site"
  hosts: webservers
  remote_user: root
  
  roles:
    - {role: pcd-common, tags: ['prepare','configure','deploy']}
    - {role: pcd-sites/apache_site, site_name: "debian.dev", site_org: "development" }
    
