---
##
# prepare|configure|deploy sites to iceburg webservers
#


# prepare and configure nashville-app-1.iceburg.net
- name: "nashville-webservers"
  hosts: nashville-webservers
  remote_user: root
  
  vars:
    # define site names to disable
    # @todo implement disabling of sites
    site_disabled_list: []
    
    default_http_site: www.iceburg.net
    default_https_site: staging.iceburg.net
    
  
  # site configurations are found in roles/pcd-sites/site/vars/<org>/<name>.yml  
  
  roles:
    - {role: pcd-common, tags: ['prepare','configure','deploy']}
    - {role: pcd-sites/apache_site, site_name: "www.iceburg.net", site_org: "iceburg" }
 #   - {role: pcd-sites/apache_site, site_name: "staging.iceburg.net", site_org: "iceburg" }
    
    
  tasks: 
    - name: set default http site
      file:
        state=link
        src={{ os_apache_sites_enabled_dir }}/{{ default_http_site }}
        dest={{ os_apache_sites_enabled_dir }}/000_default_http
      when: default_http_site is defined
      notify: 
        - apache reload
        
    - name: set default https site
      file:
        state=link
        src={{ os_apache_sites_enabled_dir }}/{{ default_https_site }}
        dest={{ os_apache_sites_enabled_dir }}/000_default_https
      when: default_https_site is defined
      notify: 
        - apache reload
        