---
##
# prepare|configure|deploy a site
#
#   preparing a site sets up mysql databases &c
#
#   configuring a site adjust server/virtualhost definitions &c
#
#   deploying a site performs git checkouts &c
#


- name: "pcd site"
  hosts: "{{ PCD_TARGET_HOST }}"
  remote_user: root
  tags: ['prepare','configure']
  
  vars_prompt:
    - name: "PCD_TARGET_HOST"
      prompt: "PCD_TARGET_HOST : Target Host/Group"
      default: "webservers"
      
    - name: "PCD_TARGET_SITE_NAME"
      prompt: "PCD_TARGET_SITE_NAME : Site Name"
      
    - name: "PCD_TARGET_SITE_ORG"
      prompt: "PCD_TARGET_SITE_ORG : Site Organization"
      

  roles:
    - {role: pcd-common, tags: ['prepare','configure','deploy']}
    - {role: pcd-sites/apache_site, site_name: "{{ PCD_TARGET_SITE_NAME }}", site_org: "{{ PCD_TARGET_SITE_ORG }}" }
    