---
##
# prepare|configure systems
#
#  preparation tasks are typically executed ONCE per host.
#
#   system preparation sets the root user's authorized key and ensures a
#      consistent, secure operating system for ansible-pcd autiomation.
#
#   + typically executed with --ask-pass option on first execution


- name: "pcd system"
  hosts: "{{ PCD_TARGET_HOST }}"
  remote_user: root

  vars_prompt:
    - name: "PCD_TARGET_HOST"
      prompt: "PCD_TARGET_HOST : Target Host/Group"
      default: "all"
      
  vars:
    # @todo amazon is deprecated, fix + test
    pcd_supported_platforms: ['Debian-7','amazon-2013.09']
    pcd_platform: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}"
    
  pre_tasks:
  
    # ensure detected platform is supported
    - fail: msg="{{ pcd_platform }} is not a supported platform!"
      when: pcd_platform not in pcd_supported_platforms
      tags: ['prepare','configure']
  
    - name: group by platform
      group_by: key="{{ pcd_platform }}"
      tags: ['prepare','configure']
      
    
- name: "Debian-7 Preparation"
  hosts: Debian-7
  remote_user: root
  
  
  roles:
    - {role: pcd-common, tags: ['prepare','configure']}
    - pcd-systems/Debian-7
    - pcd-systems/common
    