---
##
# prepare|configure|deploy the environment application
#
#  preparation tasks are typically executed ONCE per host.
#


# provision systems
- { include: pcd_system.yml, PCD_TARGET_HOST: "all" }


# prepare and configure webservers
- { include: webservers.yml }


# prepare, configure, and deploy websites
- { include: iceburg-sites.yml }

