---
##
# prepare system(s)
#  usually executed ONE time per new host. sets the root user's authorized_keys
#  and prepares a secure operating system for ansible automation.
#
#  + typically executed with --ask-pass option on first execution


- name: "system preparation - apply root user keys and system base"
  hosts: all
  remote_user: root
  
  vars_files:
    - "common/vars/paths.yml"
    - "common/vars/os_defaults.yml"
    - "common/vars/os_{{ ansible_os_family }}.yml"
  
  pre_tasks:
    - name: add {{ ansible_ssh_private_key_file }}.pub to root user's authorized keys
      authorized_key: 
        user=root 
        key="{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"
        
    - name: add {{ ansible_ssh_private_key_file }} as root user's private key
      copy: 
        dest=/root/.ssh/id_rsa 
        owner=root 
        group=root 
        mode=0600 
        src="{{ ansible_ssh_private_key_file }}"
     
  roles:
    - { role: systems/debian-7, when: "system_dist == 'debian-7'" }
    - { role: systems/amazon-2013.09, when: "system_dist == 'amazon-2013.09" }