---
##
# apache_sites deployment tasks
#

- name: ensure site destination directories
  file: path={{ item.dir }} state=directory
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized
  
- name: shallow clone sites
  git:
    depth=1
    dest={{ item.0.dir }}/{{ item.1 }}
    repo={{ item.0.git_repo }}
    version={{ item.1 }}
    accept_hostkey=yes
  when: item.0.git_repo and (apache_sites_site is not defined or apache_sites_site == item.0.name)
  with_subelements:
    - apache_sites_normalized
    - branches
  remote_user: siteop
  
- name: ensure docroot exists on sites not checked out from a repository
  file:
    path={{ item.dir }}/{{ item.docroot }}
    state=directory
  when: not item.git_repo
  with_items: apache_sites_normalized
  
- name: add site apache configs 
  template:
    dest={{ os_apache_sites_dir }}/{{ item.name }}
    src={{ item.apache_config }}
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized
  register: changed_apache_sites
  notify: 
    - apache reload
    
- name: enable [changed] apache sites
  file:
    state=link 
    src={{ os_apache_sites_dir }}/{{ item.item.name }}
    dest={{ os_apache_sites_enabled_dir }}/{{ item.item.name }}
  when: item.changed == True 
  with_items: changed_apache_sites.results

- name: disable apache sites
  file:
    state=absent 
    path={{ os_apache_sites_enabled_dir }}/{{ item.name }}
  when: apache_sites_skip_disable is not defined or not apache_sites_skip_disable
  with_items: apache_sites_disabled_list
  notify: 
    - apache reload