---
##
# apache_sites deployment tasks
#

- name: ensure site destination directories
  file: path={{ item.dir }} state=directory
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized
  

- name: shallow clone sites
  git:
    depth=1
    dest={{ item.0.dir }}/{{ item.1 }}
    repo={{ item.0.repo }}
    version={{ item.1 }}
    accept_hostkey=yes
  when: apache_sites_site is not defined or apache_sites_site == item.0.name
  with_subelements:
    - apache_sites_normalized
    - branches
  remote_user: siteop
  

- name: add site apache configs 
  template:
    dest={{ os_apache_sites_dir }}/{{ item.name }}
    src={{ item.template }}
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized
  register: handler_apache_sites
  notify: 
    - enable apache sites
    - apache reload
  