---
##
# apache_sites deployment tasks
#


- name: ensure organization directories
  file: path={{ apache_sites_user_home }}/{{ item.org }} state=directory
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized

- name: shallow clone sites
  git:
    depth=1
    dest={{ item.git_path }}
    repo={{ item.git_repo }}
    version={{ item.git_branch }}
    accept_hostkey=yes
  when: item.git and (apache_sites_site is not defined or apache_sites_site == item.name)
  with_items: apache_sites_normalized
  remote_user: siteop
  
- name: ensure site destination directories link to git checkouts
  file: dest={{ item.path }} src={{ item.git_path }} state=link
  when: item.git and (apache_sites_site is not defined or apache_sites_site == item.name)
  with_items: apache_sites_normalized
  
- name: ensure site destination directories
  file: path={{ item.path }}/{{ item.docroot }} state=directory
  when: not item.git and (apache_sites_site is not defined or apache_sites_site == item.name)
  with_items: apache_sites_normalized
  
- name: enssure site ssl keys
  copy: dest={{ os_apache_ssl_dir }}/{{ item.ssl_key | basename }} src={{ item.ssl_key }}
  when: item.ssl and (apache_sites_site is not defined or apache_sites_site == item.name)
  with_items: apache_sites_normalized
  
- name: enssure site ssl certs
  copy: dest={{ os_apache_ssl_dir }}/{{ item.ssl_crt | basename }} src={{ item.ssl_crt }}
  when: item.ssl and (apache_sites_site is not defined or apache_sites_site == item.name)
  with_items: apache_sites_normalized
  
- name: add site apache configs 
  template:
    dest={{ os_apache_sites_dir }}/{{ item.name }}
    src={{ item.apache_config }}
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized
#  register: changed_apache_sites
  notify: 
    - apache reload
    
#- name: enable [changed] apache sites
#  file:
#    state=link 
#    src={{ os_apache_sites_dir }}/{{ item.item.name }}
#    dest={{ os_apache_sites_enabled_dir }}/{{ item.item.name }}
#  when: item.changed == True 
#  with_items: changed_apache_sites.results
  
- name: enable apache sites
  file:
    state=link 
    src={{ os_apache_sites_dir }}/{{ item.name }}
    dest={{ os_apache_sites_enabled_dir }}/{{ item.name }}
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_normalized

- name: disable apache sites
  file:
    state=absent 
    path={{ os_apache_sites_enabled_dir }}/{{ item.name }}
  when: apache_sites_skip_disable is not defined or not apache_sites_skip_disable
  with_items: apache_sites_disabled_list
  notify: 
    - apache reload