---
##
# apache_sites deployment tasks
#

- name: ensure organization directory
  file: path={{ apache_sites_user_home }}/{{ item.org | default(apache_sites_default_org) }} state=directory
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_list
  

- name: shallow clone apache_sites_list
  git:
    depth=1
    dest={{ apache_sites_user_home }}/{{ item.org | default(apache_sites_default_org)  }}/{{ item.name }}-{{ item.branch | default('master') }}
    repo={{ item.repo }}
    version={{ item.branch | default('master') }}
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_list
  remote_user: siteop
  

- name: add sites to apache
  template:
    dest={{ os_apache_sites_dir }}/{{ item.name }}-{{ item.branch | default('master') }}
    src={{ item.template | default(apache_sites_default_template) }}
  when: apache_sites_site is not defined or apache_sites_site == item.name
  with_items: apache_sites_list