---
##
#  apache_sites tasks 
#

- debug: msg="apache_sites application"

- { include: "normalize.yml", tags: ['prepare,deploy'] }
#- debug: msg="{{ apache_sites_normalized }}"  

- { include: prepare.yml, tags: ['prepare'] }
- { include: deploy.yml, tags: ['deploy'], sudo: True, sudo_user: "{{ apache_sites_user }}" }
