---
##
# apache-sites normalization tasks
#
#   leverage jinja2 to help cope with deprecation of include + with_items
#
#   if apache_sites_list is not set; will default to apache_sites_list_enabled
#

- name: template normalized apache_sites_list to temp file
  local_action: template 
    dest={{ apache_sites_temp_file }}
    src=apache_sites_normalized.j2
  changed_when: False
  
- name: load normalized apache_sites_list from temp file
  include_vars: "{{ apache_sites_temp_file }}"
  
- name: unlink temp file
  local_action: file 
    path={{ apache_sites_temp_file }}
    state=absent
  changed_when: False