---
##
# apache_sites preparation tasks
#

- { include: "{{ common_tasks }}/user_add.yml", 
    user_add: {
      name: "{{ apache_sites_user }}",
      group: "{{ os_apache_config_group }}", 
      home: "{{ apache_sites_user_home }}",
      system: yes,
      github: yes,
      key: "{{ apache_sites_user_key }}"
    }
  }
  
- name: prepare mysql databases - create database
  mysql_db:
    login_host="{{ apache_sites_mysql_login_host }}"
    login_user="{{ apache_sites_mysql_login_user }}"
    login_password="{{ apache_sites_mysql_login_password }}"
    name="{{ item.1.name }}"
  when: item.0.mysql and (apache_sites_site is not defined or apache_sites_site == item.0.name)
  with_subelements:
    - apache_sites_list
    - mysql_dbs

- name: prepare mysql databases - create user, grant privs 
  mysql_user:
    login_host="{{ apache_sites_mysql_login_host }}"
    login_user="{{ apache_sites_mysql_login_user }}"
    login_password="{{ apache_sites_mysql_login_password }}"
    name="{{ item.1.user }}"
    password="{{ item.1.pass }}"
    priv="{{ item.1.name }}.*:ALL"
    append_privs=yes
    state=present
  when: item.0.mysql and (apache_sites_site is not defined or apache_sites_site == item.0.name)
  with_subelements:
    - apache_sites_list
    - mysql_dbs
