---
#
# deploys an awstats config (enables statistics on a site)
#

# @depends on pcd-apps/awstats role 

# usage:
# 
#- { include: "{{ pcd_task_add_awstats_config }}", task: {
#      site_name: "www.iceburg.net",
#      site_aliases: [],
#      log_file: "/sites/logs/www.iceburg.net.log",
#      [optional] config_template: "{{ }}"
#    }
#  }

- name: awstats > add site config
  template:
    dest={{ AWSTATS_CONF_DIR }}/awstats.{{ task.site_name }}.conf
    src={{ task.config_template | default(PCD_APP_ROLES + '/awstats/templates/awstats_default.j2') }}
  notify: awstats update
  
  