---
#
# enables a apache site
#

# @depends on pcd-services/apache role 

# usage:
#
#- { include: "{{ pcd_task_add_apache_site }}", task: {
#      name: "www.iceburg.net",
#      template: "path/to/virtualhost.j2",
#    }
#  }


- name: ensure apache site config 
  template:
    dest=/etc/ansible/conf.d/apache/virtualhosts.available/{{ task.name }}
    src={{ task.template }}
  notify: 
    - apache reload
    
- name: enable apache site
  file:
    state=link 
    src=/etc/ansible/conf.d/apache/virtualhosts.available/{{ task.name }}
    dest=/etc/ansible/conf.d/apache/virtualhosts.enabled/{{ task.name }}
  notify: 
    - apache reload
    
