---
##
# [DEBIAN] apache preparation tasks 
#

- name: ensure apache packages 
  apt: pkg={{ item }} state=present
  with_items: os_apache_packages

- name: enable modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - ssl
    - proxy
    - proxy_http
    - rewrite

- name: disable default sites
  command: a2dissite {{ item }} removes=/etc/apache2/sites-enabled/{{ item }}
  with_items:
    - default
    - default-ssl

  
- name: add {{ os_apache_config_group }} to sudoers
  lineinfile: dest=/etc/sudoers regexp="^\%{{ os_apache_config_group }}" line="%{{ os_apache_config_group }} ALL=(ALL) NOPASSWD:/usr/sbin/apache2ctl,/usr/sbin/a2ensite,/usr/sbin/a2dissite,/usr/sbin/a2enmod,/usr/sbin/a2dismod" state=present
 