---
##
# [REDHAT] apache preparation tasks 
#

- name: ensure apache packages
  yum: name={{ item }} state=present
  with_items: os_apache_packages
  
- name: configure apache to read from sites directory  
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Include {{ os_apache_sites_enabled_dir }}\/\*" insertafter="^Include conf\.d\/\*\.conf" line="Include {{ os_apache_sites_dir }}/*.enabled" state=present
  notify:
    - apache restart

- name: enable Name based VirtualHosts   
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^NameVirtualHost \*\:80" line="NameVirtualHost *:80" state=present
  notify:
    - apache restart
  