---
##
# pcd-systems/CentOS prepare
#  
      
# initialization tasks
######################

- name: setting hostname to {{ system_hostname }} [1/2]
  lineinfile: dest=/etc/sysconfig/network regexp="^HOSTNAME=" line="HOSTNAME={{ system_hostname }}" state="present"
  
- name: setting hostname to {{ system_hostname }} [2/2]
  raw: hostname {{ system_hostname }}
  
- name: setting fqdn to {{ system_fqdn }}
  lineinfile: dest=/etc/hosts state=present regexp="^127\.0\.0\.1" line="127.0.0.1 {{ system_fqdn }} {{ system_hostname }} localhost"
  
  
  
# distribution update
#####################

- name: ensure GPG key directory
  file: path={{ centos_gpg_dir }} state=directory recurse=yes
  
- name: ensure repository GPG keys
  copy: 
    src={{ item }}-{{ansible_distribution_major_version}}
    dest={{ centos_gpg_dir }}/{{ item }}-{{ansible_distribution_major_version}}
    mode=0644
  with_items:
    - RPM-GPG-KEY-CentOS
    - RPM-GPG-KEY-EPEL
    
- name: ensure repositories
  template: src={{ item }}.repo.j2 dest=/etc/yum.repos.d/{{ item }}.repo mode=0644
  with_items:
    - CentOS-Base
    - EPEL
  
- name: update system, packages to latest
  command: yum -y update 

- name: install ansible deps
  yum: name={{ item }} state=present enablerepo=epel
  with_items: os_ansible_deps


# system hardening tasks
########################

- name: denyhosts - install denyhosts
  yum: name=denyhosts state=present enablerepo=epel
  
