---
##
# varnish configuration tasks
#

- name: configure default varnish VCL
  template: 
    src=main.vcl.j2
    dest=/etc/ansible/conf.d/varnish/main.vcl
  notify: varnish restart
  
- name: template modular configurations
  template: 
    src={{ item }}
    dest=/etc/ansible/conf.d/varnish/conf/{{ item | basename | replace(".j2","") }}
  with_fileglob: "../templates/conf/*.j2"
  notify: varnish restart

- name: ensure site-specific includes file exists
  lineinfile: 
    create=yes
    line="vcl 4.0;"
    state=present
    dest=/etc/ansible/conf.d/varnish/site-includes.vcl
    
- name: template site-specific configurations
  template: 
    src={{ item }}
    dest=/etc/ansible/conf.d/varnish/sites/{{ item | basename | replace(".j2","") }}
  with_fileglob: "../templates/sites/*.j2"
  notify: varnish restart

- name: enable site-specific includes
  lineinfile: 
    line='include "/etc/ansible/conf.d/varnish/sites/{{ item | basename | replace(".j2","") }}";'
    state=present
    dest=/etc/ansible/conf.d/varnish/site-includes.vcl
  with_fileglob: "../templates/sites/*.j2"
  notify: varnish restart
  
- name: configure varnish initscript options
  template: 
    src=varnish.daemonopts.j2
    dest={{ os_sysvinit_defaults_dir }}/varnish
  notify: varnish restart

- name: ensure varnish service is running and starts on boot
  service: name=varnish state=started enabled=yes



# varnishncsa
#############

- name: ensure varnishncsa log directory
  file: path={{ VARNISH_NCSALOG_FILE | dirname }} state=directory recurse=yes

- name: configure varnishncsa
  template: 
    src=varnishncsa.daemonopts.j2
    dest={{ os_sysvinit_defaults_dir }}/varnishncsa
  notify: varnishncsa restart
  when: VARNISH_NCSALOG_ENABLE 
  
- name: ensure varnishncsa service is running and starts on boot
  service: name=varnishncsa state=started enabled=yes
  when: VARNISH_NCSALOG_ENABLE 
  
- name: ensure varnishncsa is disabled
  service: name=varnishncsa state=stopped enabled=no
  when: not VARNISH_NCSALOG_ENABLE 
