---
##
# varnish preparation tasks
#

- { include: prepare-debian.yml, when: "ansible_os_family == 'Debian'" }
- { include: prepare-redhat.yml, when: "ansible_os_family == 'RedHat'" }

- name: copy the stock default vcl for reference
  copy: src=varnish-4.default.vcl dest=/etc/varnish/varnish-4.default.vcl
