---
##
# collectd preparation configure
#

- name: register configuration
  template:
    src=collectd.conf.j2
    dest={{ collectd_config }}
  notify:
    - collectd restart
    
- name: register plugins
  template:
    src=plugins/plugins.conf.j2
    dest={{ collectd_config_dir }}/plugins.conf
  notify:
    - collectd restart
    
- name: register noise filter
  template:
    src=plugins/noise.conf.j2
    dest={{ collectd_config_dir }}/noise.conf
  notify:
    - collectd restart
  when: COLLECTD_ENABLE_NOISE_FILTER
  
- name: register csv writer
  template:
    src=plugins/csv.conf.j2
    dest={{ collectd_config_dir }}/csv.conf
  notify:
    - collectd restart
  when: COLLECTD_ENABLE_CSV_WRITER
  
  
- name: register librato writer
  template:
    src=plugins/librato.conf.j2
    dest={{ collectd_config_dir }}/librato.conf
  notify:
    - collectd restart
  when: COLLECTD_ENABLE_LIBRATO_WRITER
  
- name: remove noise filter
  file:
    path={{ collectd_config_dir }}/noise.conf
    state=absent
  notify:
    - collectd restart
  when: not COLLECTD_ENABLE_NOISE_FILTER
  
- name: remove csv writer
  file:
    path={{ collectd_config_dir }}/csv.conf
    state=absent
  notify:
    - collectd restart
  when: not COLLECTD_ENABLE_CSV_WRITER
  
- name: remove librato writer
  file:
    path={{ collectd_config_dir }}/librato.conf
    state=absent
  notify:
    - collectd restart
  when: not COLLECTD_ENABLE_LIBRATO_WRITER
  
- name: ensure collectd is running and starts on boot
  service: name=collectd state=started enabled=yes
