---
##
# pcd-services/collectd prepare
#

- { include: prepare-debian.yml, when: "ansible_os_family == 'Debian'" }

- name: ensure directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ collectd_data_dir }}"
    - "{{ collectd_config_dir }}"
    - "{{ collectd_dir }}/librato"
  
- name: fetch collectd-librato plugin 
  action: get_url 
    url=https://raw.github.com/librato/collectd-librato/master/lib/collectd-librato.py
    dest={{ collectd_dir }}/librato/collectd-librato.py
    
