---
##
#  apache_sites handlers
#

# @todo - possible to variablize handlers?
# @todo - perhaps refactor sites so site_name is determined  -- really hate name-branch redundancy.
#    ... either include with_items playbooks for each site
#    ... force specificationm of site name
#


# Debian
- name: enable apache sites
  command: sudo /usr/sbin/a2ensite {{ item.item.name }}-{{ item.item.branch | default('master') }}
  when: ansible_os_family == 'Debian' and item.changed == True 
  with_items: handler_apache_sites.results
  
  
# RedHat
- name: enable apache sites
  file:
    state=link 
    src={{ os_apache_sites_dir }}/{{ item.item.name }}-{{ item.item.branch | default('master') }}
    dest={{ os_apache_sites_dir }}/{{ item.item.name }}-{{ item.item.branch | default('master') }}.enabled
  when: ansible_os_family == 'RedHat' and item.changed == True 
  with_items: handler_apache_sites.results
  
  
- { include: "{{ common_handlers }}/apache-debian.yml", when: "ansible_os_family == 'Debian'" }
- { include: "{{ common_handlers }}/apache-redhat.yml", when: "ansible_os_family == 'RedHat'" }

  