---
##
# common system configuration
#

- debug: msg="common system configuration"

- name: ensure base software [Debian]
  apt: pkg={{ item }} state=present
  with_items: os_base_packages
  when: ansible_os_family == "Debian"
    
- name: ensure base software [RedHat]
  yum: name={{ item }} state=present
  with_items: os_base_packages
  when: ansible_os_family == "RedHat"
  
- name: fetch ps_mem.py script
  get_url:
    dest=/usr/local/bin/ps_mem.py
    force=yes
    url=https://raw.github.com/pixelb/ps_mem/master/ps_mem.py
    mode=0755
  
- name: install cronic
  copy: src={{ common_files }}/cronic.sh dest=/usr/local/bin/cronic mode=0755
  