---
##
# mysql preparation tasks
#

- name: update my.cnf
  copy: 
    src=debian-7.my.cnf
    dest=/etc/mysql/my.cnf
  notify: mysql restart
  
#@ todo - build a few configuration files based on max ram, detect and use appropriate
      