---
##
# mysql preparation tasks
#

- name: update my.cnf
  template: 
    src={{ mysql_config_template }}
    dest=/etc/mysql/my.cnf
  notify: mysql restart
  
#@ todo - build a few configuration files based on max ram, detect and use appropriate
      