---
##
# pcd-apps/awstats configure
#

# add awstats site
- { include: "{{ pcd_task_add_apache_site }}", task: {
      name: "{{ AWSTATS_SITE_NAME }}",
      template: "{{ PCD_APP_ROLES }}/awstats/templates/awstats_virtualhost.j2",
    }, sudo: False
  }

- name: run awstats_updateall.pl at specified interval
  cron: 
    name="awstats update"
    job="{{ PCD_CRON_PREFIX }}{{ AWSTATS_SITE_PATH }}/awstats_updateall.pl now"
    minute="{{ AWSTATS_CRON_MINUTE }}"
    hour="{{ AWSTATS_CRON_HOUR }}"
    state=present
    user=root
  sudo: False

- name: ensure common.conf
  template:
    dest={{ AWSTATS_CONF_DIR }}/common.conf
    src=common.conf
  notify: awstats update
  
- name: ensure htpasswd file
  htpasswd: 
    create=yes
    name={{ AWSTATS_HTPASSWD_USER }}
    password={{ AWSTATS_HTPASSWD_PASS }}
    path={{ awstats_htpasswd_file }}
    state=present
  
- name: ensure AWStats Totals script
  template:
    dest="{{ awstats_docroot }}/index.php"
    src="awstats-totals.php.j2"
    