---
##
#  pcd-apps/awstats tasks 
#

- { include: prepare.yml, 
    tags: ['prepare'],
    sudo: True,
    sudo_user: "{{ HTTPD_USER }}"
  }
  
- { include: configure.yml, 
    tags: ['configure'],
    sudo: True,
    sudo_user: "{{ HTTPD_USER }}"
  }
