---
##
# apache preparation configure
#

- name: register configurations
  template:
    src={{ item }}
    dest={{ os_apache_conf_dir }}/{{ item | basename }}
  with_fileglob: "conf/*.conf"
  notify:
    - apache restart
    
 
# Auto-Restart Apache   
- { include: "{{ pcd_task_autorestart_service }}", task: {
      service: "{{ os_apache_service }}",
      enabled: "{{ APACHE_AUTORESTART }}"
    }
  }
