---
##
# apache preparation configure
#
- name: register configurations
  template:
    src={{ item }}
    dest=/etc/ansible/conf.d/apache/configs/{{ item | basename }}
  with_fileglob: "../templates/conf/*.conf"
  notify:
    - apache restart
    
- name: register modules
  template:
    src=modules/{{ item }}
    dest=/etc/ansible/conf.d/apache/modules/{{ item }}
  with_items: apache_modules
  when: item not in APACHE_DISABLED_MODULES
  notify:
    - apache restart
    
- name: deregister disabled modules
  file:
    path=/etc/ansible/conf.d/apache/modules/{{ item }}
    state=absent
  with_items: APACHE_DISABLED_MODULES
  notify:
    - apache restart
  
- name: template apache conf
  template:
    src=httpd.conf
    dest={{ os_apache_conf }}
 
# Auto-Restart Apache   
- { include: "{{ pcd_task_autorestart_service }}", task: {
      service: "{{ os_apache_service }}",
      enabled: "{{ APACHE_AUTORESTART }}"
    }
  }
