---
##
# apache preparation tasks
#

- name: ensure apache packages 
  apt: name={{ item }} state=present
  with_items: os_apache_packages
  when: ansible_os_family == 'Debian'
  
- name: ensure apache packages 
  yum: name={{ item }} state=present
  with_items: os_apache_packages
  when: ansible_os_family == 'RedHat'
  
- name: ensure configuration directories
  file: path={{ item }} state=directory
  with_items:
    - "/etc/ansible/conf.d/apache/configs"
    - "/etc/ansible/conf.d/apache/modules"

  
- name: allow {{ HTTPD_USER_GROUP }} group to sudo execute apachectl
  lineinfile: dest=/etc/sudoers regexp="^\%{{ HTTPD_USER_GROUP }}" line="%{{ HTTPD_USER_GROUP }} ALL=(ALL) NOPASSWD:{{ os_apache_apachectl_file }}" state=present
  
- name: ensure apache site and certificate directories writable by {{ HTTPD_USER_GROUP }} group
  file: 
    path={{ item }}
    state=directory
    owner=root
    group={{ HTTPD_USER_GROUP }}
    mode=0775
  with_items:
    - "/etc/ansible/conf.d/apache/virtualhosts.available"
    - "/etc/ansible/conf.d/apache/virtualhosts.enabled"
