---
##
# apache preparation tasks
#
- fail: msg="rewriting apache role"

- { include: prepare-debian.yml, when: "ansible_os_family == 'Debian'" }
- { include: prepare-redhat.yml, when: "ansible_os_family == 'RedHat'" }
  
- name: allow {{ HTTPD_USER_GROUP }} group to sudo execute apachectl
  lineinfile: dest=/etc/sudoers regexp="^\%{{ HTTPD_USER_GROUP }}" line="%{{ HTTPD_USER_GROUP }} ALL=(ALL) NOPASSWD:{{ os_apache_apachectl_file }}" state=present
  
- name: ensure apache site and certificate directories writable by {{ HTTPD_USER_GROUP }} group
  file: 
    path={{ item }}
    state=directory
    owner=root
    group={{ HTTPD_USER_GROUP }}
    mode=0775
  with_items:
    - "{{ os_apache_sites_dir }}"
    - "{{ os_apache_sites_enabled_dir }}"
