---
##
# [DEBIAN] apache preparation tasks 
#

- name: ensure apache packages 
  apt: pkg={{ item }} state=present
  with_items: os_apache_packages

- name: enable modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - ssl
    - proxy
    - proxy_http
    - rewrite
  notify:
    - apache restart
    
- name: disable modules (save on memory)
  command: a2dismod {{ item }} removes=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - autoindex
    - status
  notify:
    - apache restart

- name: disable default sites
  command: a2dissite {{ item }} removes=/etc/apache2/sites-enabled/{{ item }}
  with_items:
    - default
    - default-ssl
    - 000-default
  notify:
    - apache restart

- name: remove default configs
  file: path={{ os_apache_conf_dir }}/{{ item }} state=absent
  with_items:
    - security
  notify:
    - apache restart
    
- name: prefer conf.d/ports.conf over default ports.conf
  lineinfile: dest=/etc/apache2/apache2.conf regexp="^#?Include ports\.conf" line="#Include ports.conf" state=present
  notify:
    - apache restart