---
##
#  pcd-apps/librato-pageloadtimes defaults 
#

PAGELOADTIMES_SITES: ['www.google.com','www.iceburg.net']

pageloadtimes_user: pageloadtimes
pageloadtimes_path: "{{ PCD_APPS_DIR }}/{{ pageloadtimes_user }}"
pageloadtimes_venv: "{{ pageloadtimes_path }}/venv"
