---
##
# backup deployment tasks
#

- name: register backup/restore scripts
  template:
    dest={{ backup_binaries }}/{{ item | basename | replace(".j2","") }}
    src={{ item }}
    mode=0700
  with_fileglob: "../templates/backup_*.sh.j2"
    

- name: schedule backups
  cron:
    name="backup of {{ item.key }}"
    hour="{{ item.value.hour }}"
    minute="{{ item.value.minute }}"
    job="sudo {{ backup_binaries }}/backup_{{ item.key }}.sh"
    state={{ item.value.state }} 
  with_dict: backup_schedule
   