---
##
# backup deployment tasks
#

- name: copy mysql backup script
  template:
    dest={{ backup_binaries }}/backup_mysql.sh
    src=backup_mysql.sh.j2
    mode=0700
    
- name: copy mysql restore script
  template:
    dest={{ backup_binaries }}/restore_mysql.sh
    src=restore_mysql.sh.j2
    mode=0700
    
    
    
  