---
##
# backup deployment tasks
#

- name: copy mysql backup script
  template:
    dest={{ backup_binaries }}/backup_mysql.sh
    src=backup_mysql.sh.j2
    mode=0700
    
- name: copy mysql restore script
  template:
    dest={{ backup_binaries }}/restore_mysql.sh
    src=restore_mysql.sh.j2
    mode=0700
    
- name: copy file backup script
  template:
    dest={{ backup_binaries }}/backup_files.sh
    src=backup_files.sh.j2
    mode=0700
    
- name: schedule daily backup of files
  cron: 
    name="backup of files"
    hour="4"
    job="{{ backup_binaries }}/backup_files.sh"
    
- name: schedule twice daily backup of mysql databases
  cron: 
    name="backup of mysql databases"
    hour="10,22"
    job="{{ backup_binaries }}/backup_mysql.sh"
    
  