---
##
# backup deployment tasks
#

- name: register backup/restore scripts
  template:
    dest={{ backup_binaries }}/{{ item | basename | replace(".j2","") }}
    src={{ item }}
    mode=0700
  with_fileglob: "../templates/scripts/*"
    
- name: schedule daily backup of files
  cron: 
    name="backup of files"
    hour="4"
    job="sudo {{ backup_binaries }}/backup_files.sh"
    
- name: schedule twice daily backup of mysql databases
  cron: 
    name="backup of mysql databases"
    hour="10,22"
    job="sudo {{ backup_binaries }}/backup_mysql.sh"
    
  
