---

- debug: msg="debian-7 bootstrap"

- name: setting hostname to {{ system_hostname }} [1/2]
  action: raw echo {{ system_hostname }} > /etc/hostname
    
- name: setting hostname to {{ system_hostname }} [2/2]
  action: raw hostname -F /etc/hostname
    
- name: setting fqdn to {{ system_fqdn }} [1/2] 
  action: lineinfile dest=/etc/hosts state=present regexp="^127\.0\.0\.1" line="127.0.0.1 localhost"
    
- name: setting fqdn to {{ system_fqdn }} [2/2] 
  action: lineinfile dest=/etc/hosts state=present regexp="^127\.0\.1\.1" line="127.0.1.1 {{ system_fqdn }} {{ system_hostname }}"
  

