---
##
#  pcd-apps/librato-pageloadtimes  tasks 
#

- { include: prepare.yml, tags: ['prepare'] }


- { include: configure.yml, 
    tags: ['configure'],
    sudo: True,
    sudo_user: "{{ pageloadtimes_user }}"
  }


- { include: deploy.yml, 
    tags: ['deploy'],
    sudo: True,
    sudo_user: "{{ pageloadtimes_user }}"
  }
