---
##
# pcd-services/mysql configure
#

- name: fetch mysqltuner.pl script
  get_url:
    dest=/usr/local/bin/mysqltuner.pl
    force=yes
    url=https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl
    mode=0755
    
- name: copy over defragmentation script
  copy:
    src="defrag_mysql.sh"
    dest={{ mysql_defrag_script }}
    mode=0755
    
- name: schedule defragmentation of databases
  cron: 
    name="defragment mysql databases"
    job="{{ PCD_CRON_PREFIX }}{{ mysql_defrag_script }}"
    minute={{ mysql_defrag_minute }}
    hour={{ mysql_defrag_hour }}
    state=present
    user=root
    
- name: ensure mysql conf.d directory
  file: path=/etc/mysql/conf.d state=directory recurse=yes

#@ todo - build a few configuration files based on max ram, detect and use appropriate
- name: update my.cnf
  template: 
    src={{ MYSQL_CONFIG_TEMPLATE }}
    dest={{ os_mysql_conf_file }}
  notify: mysql restart
  
- name: ensure mysql is running and starts on boot
  service: name={{ os_mysql_service }} state=started enabled=yes
  
      
# Auto-Restart MySQL   
- { include: "{{ pcd_task_autorestart_service }}", task: {
      service: "{{ os_mysql_service }}",
      enabled: "{{ MYSQL_AUTORESTART }}"
    }
  }
  
# mysql hardening tasks
#######################

- name: set root@localhost user's password
  mysql_user: name=root host=localhost password={{ MYSQL_ROOT_PASSWORD }} login_host=127.0.0.1 login_user=root login_password=""
  ignore_errors: yes

- name: register root user credentials
  ini_file:
    dest=/root/.my.cnf
    section=client
    option={{ item.option }}
    value={{ item.value }}
    mode=0600
  with_items:
    - { option: 'user', value: 'root' }
    - { option: 'password', value: '{{ MYSQL_ROOT_PASSWORD }}' }
    - { option: 'host', value: 'localhost' }
    
- name: set root@localhost user's password
  mysql_user: name=root host=localhost password={{ MYSQL_ROOT_PASSWORD }} login_user=root login_password={{ MYSQL_ROOT_PASSWORD }} login_host=127.0.0.1
  
- name: set root@other_local_hosts password
  mysql_user: name=root host={{ item }} password={{ MYSQL_ROOT_PASSWORD }} login_user=root login_password={{ MYSQL_ROOT_PASSWORD }} login_host=127.0.0.1
  with_items:
    - 127.0.0.1
    - ::1
    - "{{ ansible_hostname }}"

      
  