---
##
# pcd-services/mysql prepare
#

- { include: prepare-debian.yml, when: "ansible_os_family == 'Debian'" }
- { include: prepare-redhat.yml, when: "ansible_os_family == 'RedHat'" }



# mysql hardening tasks
#######################

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=yes
  
- name: register root user credentials
  ini_file:
    dest=/root/.my.cnf
    section=client
    option={{ item.option }}
    value={{ item.value }}
    mode=0600
  with_items:
    - { option: 'user', value: 'root' }
    - { option: 'password', value: '{{ mysql_root_password }}' }
    - { option: 'host', value: 'localhost' }
  
- name: set root@localhost user's password
  mysql_user: name=root host=localhost password={{ mysql_root_password }}
  ignore_errors: yes

- name: set root@other_local_hosts password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} login_user=root login_password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - "{{ ansible_hostname }}"




