---
# redhat os vars

# ansible deps
##############

os_ansible_deps:
  - MySQL-python
  - python-httplib2

# apache
########
os_apache_packages:
  - httpd
  - mod_wsgi
  - mod_ssl

os_apache_user: apache
os_apache_group: apache
os_apache_service: httpd


# certs
#######

os_certs_dir: /etc/ssl/certs

# gpg
#####

os_rpm_gpg_dir: /etc/pki/rpm-gpg

# mail
######

# location of nullmailer's "me" file
mail_me_file: /etc/nullmailer/me


# mysql
#######

os_mysql_packages:
  - mariadb-server
  
os_mysql_service: mariadb



# php
#####

# note: debian wheezy version is 5.4.4, and uses APC
#  use dotdeb to upgrade to 5.5 + built in opcache [?]

# @todo update this for yum
os_php_packages:
  - php5
  - libapache2-mod-php5
  - php5-pgsql
  - php5-mysqlnd
  - php5-curl
  - php5-mcrypt
  - php5-gd
  - php-apc
  
os_php_ini: /etc/php.ini


# rsyslog
#########

os_log_user: root
os_log_group: root

os_rsyslog_packages:
  - rsyslog
  - rsyslog-gnutls
  - logrotate
  
os_rsyslog_service: rsyslog