---
# redhat os vars

# ansible deps
##############

os_ansible_deps:
  - MySQL-python
  - python-httplib2
  - cronie

# apache
########
os_apache_packages:
  - httpd
  - mod_wsgi
  - mod_ssl

os_apache_user: apache
os_apache_group: apache
os_apache_service: httpd


# certs
#######

os_certs_dir: /etc/ssl/certs

# gpg
#####

os_rpm_gpg_dir: /etc/pki/rpm-gpg

# mail
######

# location of nullmailer's "me" file
mail_me_file: /etc/nullmailer/me


# mysql
#######

os_mysql_packages:
  - mysql-server
  
os_mysql_service: mysqld

os_mysql_error_log_file: /var/log/mysqld.log


# mysql
#######

os_mysql_conf_file: /etc/my.cnf


# php
#####

# @todo update this for yum
os_php_packages:
  - php
  - php-gd
  - php-curl
  - php-mcrypt
  - php-mysql
  - php-pecl-apc
  
os_php_ini: /etc/php.ini


# rsyslog
#########

os_log_user: root
os_log_group: root

os_rsyslog_packages:
  - rsyslog
  - rsyslog-gnutls
  - logrotate
  
os_rsyslog_service: rsyslog


# sshd
######

os_sshd_service: sshd


# sysvinit
##########

os_sysvinit_defaults_dir: /etc/sysconfig