##    
# cloud backups
#

- name: add backup user to fuse group
  user: 
    append=yes
    groups=fuse
    name={{ backup_user }}
  sudo: False
  
- { include: "{{ pcd_task_s3ql_mount }}", task: {
      nickname: "backups",
      user: "{{ backup_user }}",
      target: "{{ backup_target_dir }}",
      url: "{{ backup_s3ql_url }}",
      login: "{{ backup_s3ql_username }}",
      password: "{{ backup_s3ql_password }}"
    }
  }
  
