---
##
# prepare system(s)
#  usually executed ONE time per new host. sets the root user's authorized_keys
#  and prepares the operating system for ansible automation.
#
#  + typically executed with --ask-pass option on first execution


- name: "system preparation - apply root user keys and system base"
  hosts: all
  remote_user: root
  
  pre_tasks:
    - name: add {{ ansible_ssh_private_key_file }}.pub to root user's authorized keys
      action: authorized_key 
        user=root 
        key="{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"
        
    - name: add {{ ansible_ssh_private_key_file }} as root user's private key
      action: copy 
        dest=/root/.ssh/id_rsa 
        owner=root 
        group=root 
        mode=0600 
        src="{{ ansible_ssh_private_key_file }}"
     
  roles:
    - { role: debian-7, when: "system_base == 'debian-7'" }
    - { role: redhat-6.5, when: "system_base == 'redhat-6.5'" }