---
- name: user_add > add user {{ user_add.name }}
  user:
    name={{ user_add.name }}
    group={{ user_add.group | default('nogroup') }}
    home={{ user_add.home | default('/home/' + user_add.name) }}
    system={{ user_add.system | default(False) }}
    shell={{ user_add.shell | default('/bin/bash') }}
    
- name: user_add > set additional groups
  user:
    append=yes
    groups={{ item }}
    name={{ user_add.name }}
  when: user_add.groups is defined
  with_items: user_add.groups
  
- name: user_add > set authorized key
  authorized_key: 
    user={{ user_add.name }}
    key="{{ lookup('file', user_add.key + '.pub') }}"
  when: user_add.key is defined and user_add.key | bool
  
- name: user_add > set private key
  copy:
    dest={{ user_add.home | default('/home/' + user_add.name) }}/.ssh/id_rsa
    mode=0600
    src={{ user_add.key }}
  sudo: yes
  sudo_user: "{{ user_add.name }}"
  when: user_add.key is defined and user_add.key | bool
  
- name: user_add > set public key
  copy:
    dest={{ user_add.home | default('/home/' + user_add.name) }}/.ssh/id_rsa.pub
    mode=0600
    src={{ user_add.key }}.pub
  sudo: yes
  sudo_user: "{{ user_add.name }}"
  when: user_add.key is defined and user_add.key | bool
  
- name: user_add > ensure github vars
  include_vars: "{{ common_vars }}/github.yml"
  when: user_add.github is defined and user_add.github | bool
  
- name: user_add > add github.com signatures to known_hosts
  lineinfile:
    dest={{ user_add.home | default('/home/' + user_add.name) }}/.ssh/known_hosts
    line="{{ item }}"
    create=yes
    mode=0600
  sudo: yes
  sudo_user: "{{ user_add.name }}"
  with_items: github_knows_hosts
  when: user_add.github is defined and user_add.github | bool