---
##
#  pcd-sites/site configure
#

- name: SSL - copy key
  copy: dest={{ httpd_ssl_dir }}/{{ SITE_SSL_KEY | basename }} src={{ SITE_SSL_KEY }}
  when: SITE_HTTPS

- name: SSL - copy crt
  copy: dest={{ httpd_ssl_dir }}/{{ SITE_SSL_CRT | basename }} src={{ SITE_SSL_CRT }}
  when: SITE_HTTPS
  

# awstats
#########

- name: detect custom awstats template
  local_action: stat 
    path={{ PCD_SITE_DEFINITIONS }}/{{ site_org }}/{{ site_name }}-awstats.j2
  register: pcd_stat
  when: SITE_ENABLE_AWSTATS
  
# use custom awstats template  
- { include: "{{ pcd_task_add_awstats_config }}", task: {
      site_name: "{{ site_name }}",
      site_aliases: "{{ SITE_ALIASES }}",
      log_file: "{{ SITE_LOG_FILE }}",
      config_template: "{{ PCD_SITE_DEFINITIONS }}/{{ site_org }}/{{ site_name }}-awstats.j2",
    }, when: SITE_ENABLE_AWSTATS and pcd_stat.stat.exists
  }

# else use default awstats template
- { include: "{{ pcd_task_add_awstats_config }}", task: {
      site_name: "{{ site_name }}",
      site_aliases: "{{ SITE_ALIASES }}",
      log_file: "{{ SITE_LOG_FILE }}",
    }, when: SITE_ENABLE_AWSTATS and not pcd_stat.stat.exists
  }
  
  
# backups
#########

- name: register backup file list
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/backup_list_{{ SITE_TYPE }}.yml"
    - "../vars/backup_list_default.yml"
  when: SITE_ENABLE_BACKUP and not SITE_BACKUP_FILE_LIST


- name: add  backup file list to backup_rsync_sites_file  
  lineinfile:
    dest={{ backup_rsync_sites_file }}
    state=present
    regexp=^{{ SITE_PATH }}/{{ SITE_DOCROOT }}/{{ item }}$
    line={{ SITE_PATH }}/{{ SITE_DOCROOT }}/{{ item }}
  with_items: SITE_BACKUP_FILE_LIST
  when: SITE_ENABLE_BACKUP
    
- name: exclude site from backup_rsync_sites_file  
  lineinfile:
    dest={{ backup_rsync_sites_file }}
    state=absent
    regexp=^{{ SITE_PATH }}/{{ SITE_DOCROOT }}/
  when: not SITE_ENABLE_BACKUP




