---
##
#  pcd-sites/site configure
#

- name: SSL - copy key
  copy: dest={{ httpd_ssl_dir }}/{{ SITE_SSL_KEY | basename }} src={{ SITE_SSL_KEY }}
  when: SITE_HTTPS

- name: SSL - copy crt
  copy: dest={{ httpd_ssl_dir }}/{{ SITE_SSL_CRT | basename }} src={{ SITE_SSL_CRT }}
  when: SITE_HTTPS
  
