---
##
#  pcd-sites/site deploy
#

- name: ensure site path
  file: path={{ SITE_PATH }} state=directory
  when: SITE_GIT_REPO == ""
  
- name: ensure site docroot
  file: path={{ SITE_PATH }}/{{ SITE_DOCROOT }} state=directory
  when: SITE_GIT_REPO == ""
  
- name: git - checkout site (shallow clone)
  git:
    depth=1
    dest={{ site_git_checkouts }}/{{ SITE_GIT_REPO | regex_replace('[\ \<\>\|\\\/\:\,\;\&\*\?]*','') }}-{{ SITE_GIT_BRANCH }}
    repo={{ SITE_GIT_REPO }}
    version={{ SITE_GIT_BRANCH }}
    accept_hostkey=yes
  when: SITE_GIT_REPO != ""
  remote_user: "{{ HTTPD_USER }}"
  
- name: git - link checkout to site path
  file: state=link dest={{ SITE_PATH }} src={{ site_git_checkouts }}/{{ SITE_GIT_REPO | regex_replace('[\ \<\>\|\\\/\:\,\;\&\*\?]*','') }}-{{ SITE_GIT_BRANCH }}
  when: SITE_GIT_REPO != ""
 