---
##
#  apache_sites default vars 
#

apache_sites_user: siteop
apache_sites_user_home: /sites
apache_sites_user_key: "{{ pcd_keys_dir }}/iceburg-ocean+siteop.key"

apache_sites_default_org: iceburg       # organization
apache_sites_default_docroot: www       # docroot (relative to repo root)

apache_sites_default_apache_logformat: awstats 
apache_sites_default_apache_config: virtualhost_default.j2 


# Apache Site Definitions
# 
#   name: (required) site name, typically www.domain.com
#
#   org: (opt) site organization, defaults to {{ apache_sites_default_org }}
#
#   git_repo: (opt) git repository containing site files
#
#   branches: (opt) branches to checkout, defined as an array.
#     defaults to ["master"]. branches are checked out as; 
#       {{ apache_sites_user_home }}/<org>/<name>/<branch> }}  e.g.
#       /sites/iceburg/www.iceburg.net/master
#   
#   apache_config: (opt) template to use for apache config / virtualhost def.
#      defaults to virtualhost_default.j2.
#        can be full path, or relative to apache_sites/templates directory.
#
#   docroot: (opt) document root / path to public web files within repository,
#      defaults to "www", can be empty. "www" represents;
#        {{ apache_sites_user_home }}/<org>/<name>/<branch>/www  e.g.
#        DocumentRoot /sites/iceburg/www.iceburg.net/master/www
#
#      common repository structure 
#      /  
#      /assets  [ asset files - e.g. databases, photoshop mocks, &c ]
#      /www     [ docroot ]
#
#####################  


# default enabled sites (listed sites will be added to apache)
#   + typically overwritten by inventory vars
apache_sites_enabled_list:
  - {
    name: www.iceburg.net,
    org: "{{ apache_sites_default_org }}", 
    git_repo: "git@github.com:iceburg-net/www.iceburg.net.git",
    }
    
# default disabled sites (listed sites will be removed from apache)  
#   + typically overwritten by inventory vars
apache_sites_disabled_list:
  - {
    name: dev.example.com,
    org: "{{ apache_sites_default_org }}",
    git_repo: False
    }
  
    
# default path to private file (vars containing database credentials, &c)
apache_sites_private_file: "{{ pcd_private_dir }}/vars/apache_sites/{{ inventory_hostname }}.yml"

# default mysql credentials
apache_sites_mysql_login_host: localhost
apache_sites_mysql_login_user: root
apache_sites_mysql_login_password: ""
apache_sites_mysql_list: { }
