---
##
# [DEBIAN] pcd-services/mail prepare
#

- name: ensure mail service packages 
  apt: name={{ item }} state=present
  with_items:
    - ca-certificates
    - nullmailer
    
- name: remove default MTA packages
  apt: name={{ item }} state=absent
  with_items:
    - exim4-base
    - exim4-config
    

    