---
##
# pcd-services/nullmailer-mta prepare [REDHAT]
#

- name: ensure mailx
  yum: name=mailx state=present

- name: install nullmailer package [1/2]
  copy: 
    src=epel-{{ ansible_distribution_major_version }}/nullmailer-1.13-2.{{ ansible_architecture }}.rpm 
    dest=/root/nullmailer-1.13-2.{{ ansible_architecture }}.rpm 
  
- name: install nullmailer package [2/2]
  yum: name=/root/nullmailer-1.13-2.{{ ansible_architecture }}.rpm state=present
  
    