---
##
# pcd-services/nullmailer-mta prepare [DEBIAN]
#

- name: ensure mailx
  apt: name=heirloom-mailx state=present

- name: ensure nullmailer-mta packages 
  apt: name={{ item }} state=present
  with_items:
    - ca-certificates
    - nullmailer
    
- name: remove default MTA packages
  apt: name={{ item }} state=absent
  with_items:
    - exim4-base
    - exim4-config
    

    