---
# Global Inventory Variables (inherrited by all hosts)


# Connection defaults
#####################

ansible_ssh_private_key_file: "{{ pcd_keys_dir }}/{{ group_names[0] }}+{{ ansible_ssh_user }}.key"


# Provision defaults
####################

system_dist: debian-7
system_fqdn: "{{ inventory_hostname }}"
system_hostname: "{{ inventory_hostname_short }}"

