---
# Global Inventory Variables (inherrited by all hosts)

# Identity defaults
###################

PCD_DEFAULT_ORG: ansible


# Register PCD paths
####################

PCD_PRIVATE_DIR: "{{ inventory_dir }}/../private"
PCD_KEYS_DIR: "{{ PCD_PRIVATE_DIR  }}/keys"
PCD_CERTS_DIR: "{{ PCD_PRIVATE_DIR  }}/ssl-certs"


# Connection defaults
#####################

ansible_ssh_private_key_file: "{{ PCD_KEYS_DIR }}/{{ PCD_DEFAULT_ORG }}+{{ ansible_ssh_user }}.key"


# Provision defaults
####################

system_fqdn: "{{ inventory_hostname }}"
system_hostname: "{{ inventory_hostname_short }}"
system_uuid: "{{ ansible_product_uuid }}"


# Application Overrides
#######################

backup_s3ql_mount_opts: "--compress none"