---
#  iceburg-web-servers Inventory Variables

apache_sites_list: 
  - { org: iceburg, 
      name: www.iceburg.net,
      repo: "git@github.com:iceburg-net/www.iceburg.net.git",
      docroot: www-1
    }