---
#  nashville-web-servers Inventory Variables

PCD_DEFAULT_ORG: iceburg-nashville


# Backups
#########

backup_s3ql_enabled: False
backup_s3ql_url: gs://iceburg/{{ system_uuid }}

backup_schedule: {
  sites: { state: present, hour: "4", minute: 0 },
  files: { state: absent, hour: "2", minute: 30 },
  mysql: { state: present, hour: "10,22", minute: 0 }
}


