---
##
#  pcd-services/mysql defaults 
#

MYSQL_ROOT_PASSWORD: "{{ private_user_pass }}"
MYSQL_CONFIG_TEMPLATE: "{{ PCD_SERVICE_ROLES }}/mysql/templates/my.cnf.j2"
MYSQL_AUTORESTART: True


mysql_default_storage_engine: "MyISAM"
#mysql_default_storage_engine: "InnoDB"

mysql_defrag_script: /usr/local/bin/defrag_mysql.sh
mysql_defrag_minute: 30
mysql_defrag_hour: 4

mysql_data_dir: "{{ os_mysql_data_dir }}"



