---
##
#  apache_sites default vars 
#

apache_sites_default_apache_config: virtualhost_http.j2
apache_sites_default_apache_config_ssl: virtualhost_https.j2
apache_sites_default_apache_serveradmin: "{{ PCD_DEFAULT_USER_EMAIL }}"

# specify default sites, e.g. www.iceburg.net. must match an enabled site name.
apache_sites_default_http_site: 
apache_sites_default_https_site: 


# Apache Site Definitions
#########################
#
#   name: (required, unique) apache ServerName, typically www.domain.com
#
#   org: (opt) site organization, defaults to {{ httpd_site_org }}
#
#   apache_alias: (opt) apache ServerAlias, e.g. "domain.com domain.net"
#
#   apache_config: (opt) template to use for apache config (virtualhost def),
#     defaults to "virtualhost_http.j2". relative to apache_sites/templates
#
#   apache_config_includes: (opt) files to include in the virtualhost definition
#     defaults to: []
#
#   apache_serveradmin: (opt) apache ServerAdmin, e.g. "webmaster@domain.com",
#     default_user_email, override via apache_sites_default_apache_serveradmin
#
#   access_logfile: (opt) apache CustomLog target, e.g. "/dev/null"
#     defaults to: {{ apache_log_dir  }}/sites-{{ item.org }}.log 
#
#   ip: (opt) ip address (e.g. <VirtualHost <ip>:<port>), defaults to "*"
#   port: (opt) port, defaults to {{ apache_http_port }}
#
#   ssl: (opt) True/False to enable SSL
#      defaults to False. When True, apache_config will default to 
#      "virtualhost_https.j2", with http traffic redirected to https
#
#   ssl_ip: (opt) SSL ip (<VirtualHost <ssl_ip>:<ssl_port>), defaults to "*"/SNI
#   ssl_port: (opt) port, defaults to {{ apache_https_port }}
#   ssl_key: (opt) key file, defaults to {{pcd_certs_dir }}/<name>.key
#   ssl_crt: (opt) certificate file, defaults to  {{pcd_certs_dir }}/<name>.crt
#
#   git_repo: (opt) git repository (clone URL) containing site(s)
#
#   git_branch: (opt) branch to checkout, defaults to "master"
#     target {{ apache_sites_user_home }}/git-checkouts/<git_repo>-<git_branch>
#     creates {{ apache_sites_user_home }}/<org>/<name>-<git_branch> as link,
#     e.g. /sites/ansible/www.domain.com  --> 
#          /sites/ansible/git-checkouts/<git_repo>-<git_branch>
#
#   docroot: (opt) document root / path to public web files within repository,
#      defaults to "www", can be empty string. e.g.
#      DocumentRoot /sites/ansible/www.domain.com-master/www
#
#   redirect_url: (opt) URL to redirect site to (include http/https://)
#
#   allow_override: (opt) True (AllowOverride All) or False (AllowOverride None)
#      defaults to False.
#      apache_sites recommends disabling overrides for performance. 
#      consider adding your .htaccess content via an include.
#
#   backup_list: (opt) array of files/directories to backup.
#      paths are relative to the site's docroot. Used by the backup role.   
#
#########################

# default enabled sites (listed sites will be added to apache)
#   + typically overwritten by inventory vars
apache_sites_enabled_list: []
    
# default disabled sites (listed sites names will be removed from apache)  
#   + typically overwritten by inventory vars
apache_sites_disabled_list: []
#  - www.disabled-site.com
#  - some.other-domain.com
  
# default mysql credentials, override in private vars file
apache_sites_mysql_login_host: localhost
apache_sites_mysql_login_user: root
apache_sites_mysql_login_password: "{{ mysql_root_password }}"
apache_sites_mysql_list: { }

# default path git sites are checked into 
apache_sites_git_path: "{{ apache_sites_user_home }}/.git-apache_sites"
