---
##
# [DEBIAN] pcd-services/s3ql compile 
#
- name: ensure development dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - g++
    - libsqlite3-dev
    - python-dev
    - python-setuptools

- name: ensure s3ql base dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - python-crypto
    - python-sqlite
    - python-apsw
    - python-llfuse
    - python-lzma
    
    