---
##
# pcd-services/httpd prepare
#

- name: add {{ HTTPD_USER_GROUP }} group
  group: name={{ HTTPD_USER_GROUP }} system=yes
  

- { include: "{{ pcd_task_add_user }}", task: {
      name: "{{ HTTPD_USER }}",
      group: "{{ HTTPD_USER_GROUP }}", 
      home: "{{ HTTPD_USER_HOME }}",
      system: yes,
      github: yes,
      key: "{{ httpd_user_key }}"
    }
  }
  
- name: ensure log directories
  file: 
    path={{ item }}
    state=directory
    owner={{ os_log_user }}
    group={{ os_log_group }}
    mode=0750
  with_items:
    - "{{ HTTPD_LOG_DIR }}"
    - "{{ HTTPD_LOG_DIR }}/access"
    - "{{ HTTPD_LOG_DIR }}/errors"
    
- name: ensure ssl certificate directory
  file: 
    path={{ HTTPD_SSL_DIR }}
    state=directory
    owner={{ HTTPD_USER }}
    group={{ HTTPD_USER_GROUP }}
    mode=0775
    